name: Build Flutter APK

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      FLUTTER_STORAGE_BASE_URL: https://storage.flutter-io.cn

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.29.2'
          channel: 'stable'

      - name: Accept Android licenses
        run: yes | flutter doctor --android-licenses

      - name: Install Android SDK components
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends unzip
          yes | sdkmanager "platforms;android-35" "build-tools;35.0.0"

      - name: Get packages
        run: flutter pub get

      - name: Build APK (debug)
        run: flutter build apk --debug --no-shrink -v

      - name: Collect APKs
        run: |
          mkdir -p artifacts
          cp build/app/outputs/flutter-apk/app-debug.apk artifacts/ || true
          find $FLUTTER_ROOT/bin/cache/artifacts/engine -type f -name "*.aar" -print > aars_list.txt || true
          tar -czf artifacts/aars.tgz -T aars_list.txt || true

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: flutter-apk-and-aars
          path: artifacts
