name: Build Flutter APK

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      FLUTTER_STORAGE_BASE_URL: https://storage.flutter-io.cn
      # Use workspace as base for SDK storage
      ANDROID_SDK_WORKDIR: ${{ github.workspace }}/android-sdk

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Android SDK command-line tools and components
        run: |
          set -e
          SDK_ROOT="${ANDROID_SDK_WORKDIR}"
          mkdir -p "$SDK_ROOT/cmdline-tools"
          cd "$SDK_ROOT/cmdline-tools"
          wget https://dl.google.com/android/repository/commandlinetools-linux-11210896_latest.zip -O cmdline-tools.zip
          unzip -q cmdline-tools.zip
          rm cmdline-tools.zip
          mkdir -p "$SDK_ROOT/cmdline-tools/latest"
          mv cmdline-tools/* "$SDK_ROOT/cmdline-tools/latest/" 2>/dev/null || true
          export ANDROID_SDK_ROOT="$SDK_ROOT"
          export PATH="$ANDROID_SDK_ROOT/cmdline-tools/latest/bin:$ANDROID_SDK_ROOT/platform-tools:$PATH"
          yes | sdkmanager --sdk_root="$ANDROID_SDK_ROOT" --licenses
          sdkmanager --sdk_root="$ANDROID_SDK_ROOT" "platform-tools" "platforms;android-35" "build-tools;35.0.0"
        shell: bash
        env:
          ANDROID_SDK_WORKDIR: ${{ github.workspace }}/android-sdk

      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.29.2'
          channel: 'stable'

      - name: Get packages
        run: flutter pub get

      - name: Build APK (debug)
        run: flutter build apk --debug --no-shrink -v
