name: Build Flutter APK

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      FLUTTER_STORAGE_BASE_URL: https://storage.flutter-io.cn
      # Use workspace as base for SDK storage
      ANDROID_SDK_WORKDIR: ${{ github.workspace }}/android-sdk

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Android SDK command-line tools (robust)
        run: |
          set -euo pipefail
      
          SDK_ROOT="$GITHUB_WORKSPACE/android-sdk"
          mkdir -p "$SDK_ROOT/cmdline-tools"
          REPO_XML="https://dl.google.com/android/repository/repository2-1.xml"
      
          echo "Fetching repository index..."
          curl -sSfL "$REPO_XML" -o repo.xml
      
          echo "Parsing for latest Linux commandlinetools URL..."
          URL=$(grep -oP '(?<=<url>).+commandlinetools-linux[^<]+_latest.zip(?=</url>)' repo.xml | head -n 1)
      
          if [ -z "$URL" ]; then
            echo "Failed to find commandlinetools URL in repository XML, aborting."
            exit 1
          fi
      
          # If URL is relative, prefix with dl.google.com
          if [[ "$URL" != http* ]]; then
            URL="https://dl.google.com/android/repository/${URL#./}"
          fi
      
          echo "Downloading: $URL"
          wget -q --show-progress -O cmdline-tools.zip "$URL"
      
          unzip -q cmdline-tools.zip -d cmdline-tools
          rm cmdline-tools.zip
      
          # Move into expected layout: cmdline-tools/latest/...
          mkdir -p "$SDK_ROOT/cmdline-tools/latest"
          mv cmdline-tools/* "$SDK_ROOT/cmdline-tools/latest/" 2>/dev/null || true
          rmdir cmdline-tools 2>/dev/null || true
      
          export ANDROID_SDK_ROOT="$SDK_ROOT"
          export PATH="$ANDROID_SDK_ROOT/cmdline-tools/latest/bin:$ANDROID_SDK_ROOT/platform-tools:$PATH"
      
          yes | sdkmanager --sdk_root="$ANDROID_SDK_ROOT" --licenses
          sdkmanager --sdk_root="$ANDROID_SDK_ROOT" "platform-tools" "platforms;android-35" "build-tools;35.0.0"
      
        shell: bash
        env:
          GITHUB_WORKSPACE: ${{ github.workspace }}
          
      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.29.2'
          channel: 'stable'

      - name: Get packages
        run: flutter pub get

      - name: Build APK (debug)
        run: flutter build apk --debug --no-shrink -v
